### ISSUE TITLE
overlap mode and extend mode?

### ISSUE THREAD

**Issue by jianshu93** [ruanjue/bsalign#2]
Dear BSAlign team,

I tried both mode, overlap mode is more like a semi-global mode that ignore gaps at both ends right, so only the overlap region that matters. However, for the extend mode, only gaps at the beginning of sequence 1 are extended while gaps at the end of it were not extended. I just trimmed the first sequence  for 50 bp at both ends of it to do the testing. Any reasons for that?

Thanks,

Jianshu

**Comment by ruanjue** [comment]
`overlap` ignore gaps at both ends, `entend` ignore the right end. Those are common used in reads overlapping of genome assembly.

**Comment by jianshu93** [comment]
Hi @ruanjue,

Thanks for clarification. It seems global and overlap mode are enough for me, just do not know in genome assembly the extend mode is the common practice (not an assembly person). Amazing software and amazing performance. Definitely useful for many projects.  I can imagine when combined with some approximate alignment softwares such as ChainX (based on MEMs or minimizers), an extremely fast large-scale sequence alignment and search tool can be developed.

Jianshu
